# Generated by Django 3.0.2 on 2021-05-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainimage', models.ImageField(blank=True, upload_to='vsapp/')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('preview_text', models.TextField(max_length=50, verbose_name='Preview Text')),
                ('detail_text', models.TextField(max_length=100, verbose_name='Detail Text')),
                ('price', models.FloatField()),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
            },
        ),
    ]
