# Generated by Django 3.0.2 on 2021-05-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsapp', '0006_auto_20210522_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='detail_text',
            field=models.TextField(max_length=500, verbose_name='Detail Text'),
        ),
    ]
