# Generated by Django 3.0.2 on 2021-11-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsapp', '0009_auto_20211104_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='directors',
        ),
        migrations.RemoveField(
            model_name='review',
            name='stars',
        ),
        migrations.RemoveField(
            model_name='review',
            name='writers',
        ),
        migrations.AddField(
            model_name='movies',
            name='directors',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='stars',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='writers',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
