# Generated by Django 3.0.2 on 2021-05-22 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vsapp', '0002_auto_20210521_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='price',
        ),
    ]
