# Generated by Django 3.0.2 on 2021-05-22 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsapp', '0003_remove_movies_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='genre',
            field=models.CharField(default='genre', max_length=20),
        ),
        migrations.AddField(
            model_name='movies',
            name='release_period',
            field=models.CharField(default='release period', max_length=20),
        ),
    ]
