# Generated by Django 3.0.2 on 2021-05-22 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsapp', '0005_auto_20210522_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='preview_text',
            field=models.TextField(max_length=150, verbose_name='Preview Text'),
        ),
    ]
