# Generated by Django 3.0.2 on 2021-11-07 20:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vsapp', '0010_auto_20211104_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='created_date',
        ),
        migrations.AddField(
            model_name='review',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='review',
            name='user_name',
            field=models.CharField(default='Unknown user', max_length=100),
        ),
    ]
