# Generated by Django 3.0.2 on 2021-11-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsapp', '0013_auto_20211119_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_slug',
            field=models.SlugField(default=''),
        ),
    ]
