# Generated by Django 3.0.2 on 2021-11-19 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vsapp', '0014_review_review_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review_slug',
            new_name='slug',
        ),
    ]
