# Generated by Django 3.2 on 2022-01-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsapp', '0015_auto_20211119_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
